SevenTV/Extension

.github/workflows/build-pr.yaml
Adding a github workflow to automatically build pull requests and output an artifact
=> Pull Request Build Workflow

src/Content/App/App.tsx, src/Content/Content.tsx, src/Page/FFZ/FrankerFaceZ.Addon.ts
Fixing a few issues with the WebSocket and the FrankerFaceZ Add-On #63
=> Fix FFZ Add-on WebSocket & Loading Issues 

src/Content/Components/EmoteComponent.tsx, src/Global/EmoteStore.tsx, src/Page/Components/MessageBody.tsx
Creating various improvements to the performance of emoji rendering, by removing unnecessary/duplicate calls to the json index file.
This aims to fix #17
=> Improve Emoji Performance

src/Content/App/App.tsx, src/Content/Runtime/TabCompleteDetection.tsx, src/Page/FFZ/FrankerFaceZ.Addon.ts, src/Page/Page.tsx, src/Page/Runtime/TabCompletion.tsx
Resolving clashing issues with tab-completion and implementing full cursor iteration
=> Fix Tab-Completion & Implement Cursor Iteration

src/Content/Components/EmoteComponent.tsx, src/Content/Components/MainComponent.tsx, src/Content/Components/TooltipComponent.tsx, src/Content/Runtime/MessageRenderer.tsx, src/Content/Runtime/MessageTree.tsx, src/Global/EmoteStore.tsx
Improving the performance of the extension's emote renderer, reducing CPU and Memory usage
=> Emote Renderer Optimization

src/Content/App/App.tsx, src/Content/Components/EmoteMenu/EmoteMenuButton.tsx, src/Global/API.ts
Reducing the amount of network requests sent by the client, by merging GQL queries into a single request
=> Optimize API Requests

src/Config.ts, src/Global/WebSocket/WebSocket.ts
Adding some randomness around websocket reconnection back-off to prevent a self-DDoS situation
=> WebSocket Reconnect Jitter

src/Content/App/App.tsx, src/Content/Components/EmoteComponent.tsx, src/Content/Components/MainComponent.tsx, src/Content/Components/TooltipComponent.tsx, src/Content/Runtime/MessageRenderer.tsx, src/Global/API.ts, src/Global/Badge.ts, src/Global/EmoteStore.tsx
Implementing 7TV Chat Badges into the native extension
=> 7TV Chat Badges

src/Global/EmoteStore.tsx, src/Page/FFZ/FrankerFaceZ.Addon.ts, src/Style/Style.scss
Adding support for zero-width emotes (using the new visibility flag `1 << 7`)
=> Zero Width Emotes

src/Content/Components/EmoteMenu/EmoteMenu.tsx, src/Style/Style.scss
Adding a search function to the emote menu
=> Emote Menu Search

src/Content/App/App.tsx, src/Content/Runtime/TabCompleteDetection.tsx
Fixing consistency issues with autocomplete and some QoL improvements like adding a space at the end of the cursor and autocompleting twitch emotes
This should fix #84
=> Autocompletion Improvements

package-lock.json, package.json, public/manifest.json, src/Content/App/App.tsx, src/Content/Components/EmoteComponent.tsx, src/Content/Components/EmoteMenu/EmoteMenu.tsx, src/Content/Components/MainComponent.tsx, src/Content/Components/Settings/SettingsComponent.tsx, src/Content/Components/TooltipComponent.tsx, src/Content/Content.tsx, src/Global/Badge.ts, src/Global/EmoteStore.tsx, src/Global/Util.ts, src/Page/Page.tsx, src/Style/Components/Settings.scss, src/Style/Components/Tooltip.scss, src/Style/Style.scss
Adding a settings menu, allowing users to choose preferences on the extension
=> Settings Menu

src/Content/Components/EmoteMenu/EmoteMenu.tsx, src/Content/Components/MainComponent.tsx, src/Global/Util.ts, src/Page/Page.tsx, src/Page/Runtime/ChatListener.ts, src/Page/Util/Twitch.ts, src/Style/Components/Settings.scss
Bringing moderation events, such as bans, timeouts and message deletions into public view
=> Public Mod Actions

src/Content/Runtime/MessageTree.tsx, src/Global/EmoteStore.tsx, src/Style/Style.scss
Adding an option for blurring unlisted emotes in the chat
=> Blur Unlisted Emotes

src/Content/Components/MainComponent.tsx, src/Content/Components/Settings/SettingsComponent.tsx
=> Use `storage.local` instead of sync

src/Content/App/App.tsx, src/Content/Components/MainComponent.tsx, src/Content/Components/Settings/SettingsComponent.tsx, src/Content/Runtime/MessageTree.tsx, src/Content/Runtime/Settings.ts, src/Content/Runtime/TabCompleteDetection.tsx
Moving the settings into a proper class that can be used across the app
=> Refactor Settings Getter

src/Content/App/App.tsx, src/Page/FFZ/FrankerFaceZ.Addon.ts, src/Page/Page.tsx
=> Events - Fix previous channel not being unsubscribed and filter event by target channel

src/Content/Runtime/MessageTree.tsx, src/Content/Runtime/Settings.ts, src/Global/Util.ts, src/Page/Page.tsx, src/Page/Runtime/InputManager.tsx, src/Page/Util/Twitch.ts, src/Style/Components/Settings.scss
Adding a setting to alllow bypassing the notice "your message is identical to the one you sent within the last 30 seconds", support for Ctrl+Enter and retrieving historical messages via arrow keys
=> Duplicate Message Bypass, Ctrl+Enter & History Navigation

src/Content/App/App.tsx, src/Content/Runtime/Settings.ts, src/Content/Runtime/TabCompleteDetection.tsx
Adding active chatters to the list of auto-completable values (optional)
=> Auto-Complete chatters

src/Style/Style.scss
Finalizing scaling changes started by #113 and tracked in #111
=> Finalize Emote Scaling

src/Global/EmoteStore.tsx, src/Page/Page.tsx
Implementing an emote weight value, at this time calculated by the standard global / provider check.
=> Emote Weight

src/Content/Runtime/MessageRenderer.tsx, src/Page/Runtime/ChatListener.ts, src/Page/Util/MessagePatcher.tsx
=> Fix Chat Window Crash Issue

src/Content/Runtime/MessageTree.tsx, src/Global/EmoteStore.tsx, src/Page/Util/Twitch.ts, src/Style/Style.scss
=> Fix Twitch Cheermotes

src/Page/Page.tsx, src/Page/Runtime/InputManager.tsx
=> Fix Ctrl+Enter Keybind

src/Content/Runtime/MessageTree.tsx, src/Style/Style.scss
=> Fix Chat Spacing between Text & Emotes

public/manifest.json, src/Config.ts, src/Content/App/App.tsx, src/Global/API.ts, src/Global/EmoteStore.tsx, src/Page/Page.tsx, src/Page/Util/Twitch.ts
Implementing BetterTTV and FrankerFaceZ APIs within the extension itself in order to avoid rate limiting issues currently facing the 7TV API Proxy
=> Local Third Party API Implementation

public/manifest.json, src/Background/Background.tsx, src/Config.ts, src/Content/App/App.tsx, src/Content/Runtime/Settings.ts, src/Global/API.ts, src/Global/Badge.ts, src/Global/EmoteStore.tsx, src/Page/Page.tsx, src/Page/Runtime/Avatars.ts
Adding support for 7TV custom animated avatars in the extension
=> Animated Avatars

src/Background/Background.tsx, src/Sites/youtube.com/Runtime/ChatObserver.ts, src/Sites/youtube.com/Util/YouTube.ts, src/Sites/youtube.com/youtube.tsx
Re-rendering messages and re-inserting the emote menu button when the chat rerenders
=> Handle full chat rerender

src/Sites/twitch.tv/Components/MessageRenderer.tsx, src/Sites/twitch.tv/Components/MessageTree.tsx, src/Sites/twitch.tv/Runtime/ChatListener.ts, src/Sites/twitch.tv/Util/Twitch.ts, src/Style/Style.scss
Adding an highlight on messages that mention the current user
=> Mention Highlight

src/Background/Background.tsx, src/Content/App/App.tsx, src/Global/Events/EventAPI.ts, src/Sites/twitch.tv/twitch.tsx
Reinstating the Event API implementation post-refactor
=> Reinstate the EventAPI

src/Sites/app/EmbeddedUI.tsx, src/Style/Style.scss
Fixed an issue with the emote menu being a few pixels too large and not clickable on the sides outside the logo.
Made the 7TV settings button have a background on hover.
=> Menu button fixes

src/Sites/youtube.com/Runtime/Tokenizer.ts, src/Sites/youtube.com/Util/YouTube.ts
Renders links as clickable when the sender is a moderator in the channel.
=> Fix Clickable hyperlinks in youtube chat

src/Sites/youtube.com/Util/Divisor.tsx, src/Sites/youtube.com/youtube.tsx, src/Style/Components/YouTube/TheaterMode.scss
Fixes offset when viewing vertical youtube streams in true theatre mode.
Improves the divisor a bit.
=> True theatre mode improvements

changelog.md, src/Sites/twitch.tv/twitch.tsx
Fixing emote events not updating in chat
=> Fix Emote Events

changelog.md, src/Sites/app/SiteApp.tsx, src/Sites/twitch.tv/Runtime/ChatListener.ts, src/Style/Style.scss
Added support for non ascii names by moving the paints css class one element back and removing the opacity on the ascii name. 
Also made static parts of the paints style its own css style
=> Added support for non-ascii names

changelog.md, src/Sites/app/Runtime/TabCompleteDetection.tsx, src/Sites/twitch.tv/Runtime/InputManager.tsx, src/Sites/twitch.tv/Util/Twitch.ts, src/Sites/twitch.tv/twitch.tsx, src/Style/Style.scss
Fix for twitch's new chatbox update.
=> Twitch Slate Chat Input Fix

changelog.md, src/Sites/twitch.tv/Runtime/InputManager.tsx, src/Sites/twitch.tv/Util/Twitch.ts, src/Sites/twitch.tv/twitch.tsx
Lets the extension load while in mod view
Fixes #244
=> Fix for mod view

src/Style/Style.scss
(Making a new PR for this as last PR I committed to my repo and the dev branch so I couldn't make additional commits/edits.)(Previous PR: https://github.com/SevenTV/SevenTV/pull/220)
https://github.com/SevenTV/SevenTV/commit/c732e5458814dd5900501a4d68c9202e3efd337c prevents other CSS with higher priority from altering the image width since height is !important the emoji is unable to adapt to the higher priority CCS and just takes the height with it
https://github.com/SevenTV/SevenTV/commit/be7aa89f99370c11990aa710724a566f6fc60ff0 fixes the logo being slightly blurry on the site
With changes:
Prior to changes:
=> Fixed 2 minor CSS issues

CHANGELOG-nightly.md, src/site/twitch.tv/modules/chat/ChatList.vue, src/site/twitch.tv/modules/chat/ChatModule.vue
Adding an option to customize the font sizing in chat
=> Chat Font Size Option

CHANGELOG-nightly.md, package.json, src/site/twitch.tv/modules/chat/ChatList.vue
Fixes issue causing emotes to sometimes display as broken images
=> Don't parse fake emotes patched into messages by BTTV and FFZ

CHANGELOG-nightly.md, src/composable/chat/useChatHighlights.ts, src/site/global/settings/SettingsConfigHighlights.vue, src/site/twitch.tv/modules/chat/ChatList.vue, src/site/twitch.tv/modules/emote-menu/EmoteMenuModule.vue
This fixes some issues with highlights
- Modifying an highlight when "Flash Title" was turned on did not work
- Turning off "Play sound on mention" also turned custom sounds for highlights
=> Fix Highlights Save & Sound

src/common/Constant.ts, src/site/global/settings/CategoryDropdown.vue, src/site/global/settings/Settings.ts, src/site/global/settings/SettingsNode.vue, src/site/global/settings/SettingsViewConfigCat.vue
Adding a little green bubble for settings that are new or weren't seen before
=> Settings: Unseen Bubble

CHANGELOG-nightly.md, package.json, src/composable/useFrankerFaceZ.ts, src/site/twitch.tv/modules/chat-input/ChatInput.vue
Also should fix performance issues with the chat input
=> Fix tab complete not properly considering Slate tokens

CHANGELOG-nightly.md, src/site/twitch.tv/modules/chat/ChatModule.vue, src/site/twitch.tv/modules/chat/components/message/UserMessage.vue
Allows changing how deleted message appear in chat, between hidden, dimmed, strikethrough and keep.
=> Deleted Message Style

CHANGELOG-nightly.md, package.json, src/composable/tray/tray.d.ts, src/site/twitch.tv/modules/chat/ChatController.vue, src/site/twitch.tv/modules/chat/components/message/UserMessageButtons.vue, src/site/twitch.tv/modules/chat/components/tray/ChatTray.ts, src/site/twitch.tv/modules/chat/components/tray/ChatTray.vue, src/site/twitch.tv/modules/chat/components/tray/ReplyTray.vue, src/site/twitch.tv/modules/chat/components/tray/tray.d.ts
This changes the threading behavior so that it matches native Twitch, by making threaded replies use the original message being replied to, rather than replying to a reply.
Closes #386
=> Fix Threading Behavior

src/assets/svg/icons/VolumeIcon.vue, src/assets/svg/icons/VolumeMutedIcon.vue, src/composable/chat/useChatMessages.ts, src/composable/useUpdater.ts, src/site/ModuleWrapper.vue, src/site/global/Global.vue, src/site/twitch.tv/modules/emote-menu/EmoteMenuSet.vue, src/site/twitch.tv/modules/qol/QoL.vue, src/site/twitch.tv/modules/qol/QoLModule.vue, src/site/twitch.tv/modules/qol/VolumeButton.vue, src/site/twitch.tv/modules/qol/VolumeSlider.vue, src/types/app.d.ts, src/types/tw.module.d.ts, vite.config.ts
Small things to improve the user experience
=> Small QoL Tweaks

.github/workflows/ci.yaml
=> fix: bad ci condition syntax

src/site/twitch.tv/modules/chat/ChatModule.vue, src/site/twitch.tv/modules/chat/components/message/UserMessage.vue
=> feat:add seconds to timestamp in twitch chat

src/site/global/Changelog.vue, src/site/global/settings/SettingsNode.vue, src/site/global/settings/SettingsViewHome.vue
=> Fix subtitle text contrast

src/site/global/settings/SettingsMenu.vue, src/site/twitch.tv/modules/emote-menu/EmoteMenu.vue
=> Add colored borders to focused inputs

package.json, vite.config.hosted.ts
This makes the size of the hosted bundle smaller, by enabling minify and switching chunking from manual to auto. This necessitated moving away from vite's library mode.
=> Optimize Hosted Bundle

CHANGELOG-nightly.md, package.json, src/assets/gql/tw.chat-replies.gql.ts, src/assets/gql/tw.gql.d.ts, src/common/Transform.ts, src/site/twitch.tv/modules/chat/components/tray/ReplyTray.vue
Updating the implementation of Twitch's reply threads to utilize the proper data from the API, rather than using cached data from the current chat context.
Closes #443 #491
=> Reply Threads Full Implementation

.github/workflows/check-changelog.yaml, .github/workflows/ci.yaml, CHANGELOG-nightly.md
Adding a CI job to request contributors add a changelog entry
=> ci: changelog check

.github/workflows/ci.yaml, CHANGELOG-nightly.md, src/site/twitch.tv/modules/chat/components/message/Emote.vue
Fixes #452 where the opened detailed emote card would go under the message if the opened emote wasn't the last one 
Before:
After:
=> fix/emote-card-positioning: Fix emote card positioning

CHANGELOG-nightly.md, src/site/twitch.tv/modules/chat/ChatList.vue, src/site/twitch.tv/modules/chat/ChatModule.vue, src/site/twitch.tv/modules/chat/ChatPubSub.vue
=> feat: add option to hide suspicious user highlight

README.md
Added [shields](https://github.com/badges/shields) to the README and rearranged some things.
README Screenshot:
=> Added shields to the README

CHANGELOG-nightly.md, locale/en_US.yaml, src/common/Transform.ts, src/site/twitch.tv/modules/emote-menu/EmoteMenuSet.vue, src/site/twitch.tv/modules/emote-menu/EmoteMenuTab.vue
Changed white Smileys to Emojis representing the group.
=> Added emojis as icons for the emoji groups

CHANGELOG-nightly.md, CHANGELOG.md, package.json, src/site/twitch.tv/modules/sidebar-previews/SidebarCard.vue
Tentatively fixes an issue which caused the sidebar to crash sometimes, seemingly due to a new twitch experiment.
=> fix: sidebar crash

src/app/paint-tool/PaintToolGradientStop.vue, src/app/paint-tool/PaintToolMaker.vue, src/app/paint-tool/PaintToolShadow.vue
=> paint-tool(fix): missing shadows data on import

src/app/paint-tool/PaintTool.vue, src/app/paint-tool/PaintToolMaker.vue
=> paint-tool(fix): scrollbar styling

CHANGELOG-nightly.md, src/site/kick.com/modules/chat/ChatAutocomplete.vue, src/site/kick.com/modules/chat/ChatController.vue, src/site/kick.com/modules/chat/ChatMessage.vue
this fixes some style issues with text overflow & emoji behavior
=> site/kick(fix): text wrapping & emojis

CHANGELOG.md, package.json, src/site/kick.com/modules/chat/ChatMessage.vue, src/site/kick.com/modules/chat/ChatObserver.vue
=> kick(fix): scroller fix attempt #2

CHANGELOG-nightly.md, src/site/kick.com/modules/chat/ChatAutocomplete.vue, src/site/kick.com/modules/chat/ChatController.vue, src/site/kick.com/modules/chat/ChatModule.vue
This adds colon (:) autocompletion (colon-complete) to kick for 7TV emotes
=> kick(feat): Colon Autocompletion

locale/en_US.yaml, src/app/emote-menu/EmoteMenuSet.vue, src/app/emote-menu/EmoteMenuTab.vue, src/app/options/views/Onboarding/OnboardingPromo.vue, src/app/settings/Settings.ts, src/app/settings/SettingsMenu.vue, src/app/store/Store.vue, src/app/store/StoreSubscribeButton.vue, src/app/store/egvault.ts, src/composable/useActor.ts, src/site/kick.com/KickSite.vue, src/site/twitch.tv/TwitchSite.vue
Adding some promotional slots for 7TV subscriptions to end users who are not subscribed
=> Personal Emotes Promotion

CHANGELOG-nightly.md, src/site/kick.com/modules/chat/ChatMessage.vue
this makes zero-width work on kick
=> fix(kick): zero-width emote rendering

CHANGELOG-nightly.md, src/app/chat/UserCard.vue, src/assets/gql/tw.user-card.gql.ts
Updating GraphQL queries for recent API changes, which caused data such as message history to not load in user cards
=> fix(twitch/usercard): outdated queries

CHANGELOG-nightly.md, src/assets/svg/icons/IconForSettings.vue, src/assets/svg/icons/PlayerIcon.vue, src/site/twitch.tv/modules/player/PlayerContentWarning.vue, src/site/twitch.tv/modules/player/PlayerController.vue, src/site/twitch.tv/modules/player/PlayerModule.vue, src/types/tw.module.d.ts, src/types/twitch.d.ts
This adds an option to hide the new "mature content" warning labels on Twitch.
=> feat(twitch): hide content warning dialog

CHANGELOG-nightly.md, locale/en_US.yaml, src/app/settings/CategoryDropdown.vue, src/app/settings/SettingsMenu.vue, src/app/settings/SettingsNode.vue, src/app/settings/SettingsViewConfigCat.vue, src/app/settings/SettingsViewHome.vue, src/site/kick.com/KickSite.vue, src/site/kick.com/modules/chat/ChatModule.vue, src/site/kick.com/modules/chat/ChatObserver.vue, src/site/kick.com/modules/settings/SettingsChatHook.vue, src/site/kick.com/modules/settings/SettingsModule.vue, src/site/twitch.tv/modules/chat/ChatModule.vue, src/types/kick.module.d.ts
Overhauling the stylesheet for settings to use CSS Grid and showing the settings menu on kick
=> chore(settings): cleanup, grid & kick compatibility

CHANGELOG-nightly.md, src/site/kick.com/modules/chat/ChatModule.vue, src/site/kick.com/modules/chat/ChatObserver.vue
Adding a Message Batching option for chat on kick.com
=> kick/chat(feat): message batching

CHANGELOG-nightly.md, src/app/chat/msg/55.PaidMessage.vue, src/app/settings/SettingsMenu.vue, src/site/twitch.tv/index.ts, src/site/twitch.tv/modules/chat/ChatList.vue, src/types/twitch.messages.d.ts
this adds formatting support for the new "hype chat" feature on twitch
=> twitch/chat(feat): hype chat

src/site/kick.com/modules/chat/ChatObserver.vue
rendering
it renders
the messages
=> kick/chat(fix): batch rendering autoscroll

CHANGELOG-nightly.md, src/site/twitch.tv/modules/chat/ChatList.vue
=> twitch/chat(fix): chatter autocomplete

src/app/settings/SettingsViewHome.vue
everyday i come ever closer to pulling firefox support entirely
=> settings(chore): skip twtr. widget on firefox

package.json, yarn.lock
#739 added an unnecessary dependency, which is currently unused.
=> Remove unused dependancy introduced in #739

.env.dev, .env.production, CHANGELOG-nightly.md, src/common/Transform.ts, src/types/app.d.ts, src/worker/worker.http.ts
Fixes regression introduced in #797
=> Restore EventAPI updates for channel sets, and remove static cosmetic fetching

CHANGELOG-nightly.md, src/app/emote-menu/EmoteMenu.vue
=> Fix spacing between emote providers and emote set when live search is enabled

CHANGELOG-nightly.md, src/worker/worker.driver.ts
=> fix: delete stale global emote sets

CHANGELOG-nightly.md, src/site/twitch.tv/modules/hidden-elements/HiddenElementsModule.vue, src/site/twitch.tv/modules/hidden-elements/hiddenElements.ts
Solves issue/feature request #994
Disabled:
Enabled:
=> feat(twitch): hide community challenge contributions

src/site/kick.com/modules/chat/ChatModule.vue
An oversight has caused the chat module to not inject on routes besides the channel route. This PR fixes that.
--
=> fix(kick): add chatroom routes

CHANGELOG-nightly.md, src/common/ReactHooks.ts
A small oversight caused the React hooks to not be able to find the root node. 
--
=> fix: react 18 support

src/site/kick.com/modules/chat/ChatMessage.vue, src/site/kick.com/modules/chat/ChatObserver.vue
=> fix(kick): 7TV chat badges

src/common/Input.ts, src/common/Tokenize.ts, src/common/Transform.ts, src/site/kick.com/modules/chat-input/ChatInput.vue, src/site/kick.com/modules/chat-input/ChatInputModule.vue, src/site/kick.com/modules/chat/ChatObserver.vue, src/site/kick.com/modules/emote-menu/EmoteMenu.vue, src/site/kick.com/modules/emote-menu/EmoteMenuModule.vue, src/site/twitch.tv/modules/chat-input/ChatInput.vue, src/site/twitch.tv/modules/chat-input/ChatInputCarousel.vue, src/types/kick.d.ts, src/types/kick.module.d.ts
=> feat(kick): add emote menu and autocomplete

src/site/kick.com/modules/chat-input/ChatInput.vue
=> fix(kick): kick chat history

CHANGELOG-nightly.md, src/app/paint-tool/PaintTool.vue
People always think the paint tool is used for actually changing their paint. To prevent this a note was added on top of the paint tool: 
=> Feat: Added note about the purpose of the paint tool

CHANGELOG-nightly.md, src/site/twitch.tv/modules/sidebar-previews/SidebarPreviewsModule.vue, src/types/twitch.d.ts
Adds the option of expanding the sidebar on hover
=> Expand sidebar on hover

src/app/chat/Emote.vue
Fix for https://github.com/SevenTV/Extension/issues/1055 issue.
=> fix: generic emoji click causes callstack exceeded

src/site/global/GlobalSettings.ts
=> fix(twitch): unable to send emote message

CHANGELOG-nightly.md, src/composable/useCosmetics.ts
Fixes personal emote sets if the user has multiple sets
=> Fix personal emote sets

src/worker/worker.events.ts, vite.config.worker.mts
=> Include dev version in api params

CHANGELOG-nightly.md, package.json, src/site/twitch.tv/modules/chat/ChatController.vue, src/site/twitch.tv/modules/chat/ChatList.vue, src/site/twitch.tv/modules/chat/ChatModule.vue, src/types/twitch.d.ts
=> fix(twitch/chat): add cooldown timer

.github/workflows/ci.yaml
=> ci: upload-artifact v4

.github/workflows/ci.yaml
=> ci: artifact-download v4

CHANGELOG-nightly.md, CHANGELOG.md, package.json, src/app/chat/UserCard.vue, src/app/chat/UserCardMessageList.vue, src/common/ReactHooks.ts, src/composable/chat/useChatModeration.ts, src/composable/useApollo.ts, src/site/global/components/EmoteCard.vue, src/site/kick.com/modules/chat/ChatModule.vue, src/site/twitch.tv/TwitchSite.vue, src/site/twitch.tv/modules/chat/components/tray/ReplyTray.vue
=> fix(twitch): twitch apollo hook

src/composable/chat/useChatProperties.ts, src/site/global/GlobalSettings.ts, src/site/twitch.tv/modules/chat-input/ChatSpam.vue, src/site/twitch.tv/modules/chat/ChatController.vue
=> Tomfoolery

src/site/site.ts
=> Remove hosted-site
