src/Content/App/App.tsx, src/Content/Runtime/TabCompleteDetection.tsx, src/Global/EmoteStore.tsx, src/Page/Runtime/ChatListener.ts, src/Page/Util/Twitch.ts
Quality of Life changes to Auto-completion
- Adding a space at the end of the active cursor
- Resetting the cursor when the user presses spacebar
- Adding support for Twitch emotes
=> Autocomplete QoL

src/Content/Runtime/MessageTree.tsx, src/Global/EmoteStore.tsx, src/Style/Style.scss
Changing how zero-width emotes render, by adding a css class to the emote preceding a zero-width emote. The previous method was causing a reversed order.
=> Fix Zero-Width Positioning

src/Content/Runtime/TabCompleteDetection.tsx, src/Page/Page.tsx, src/Page/Runtime/TabCompletion.tsx
* Allow the ability to tab complete words other than the last one
* Reset tab complete cursor when input has been changed
* Finish tab complete when the user unfocuses the chat box
=> Better tab-complete

src/Style/Style.scss
It causes problems with larger emotes such as BTTV's `NaM`
=> Remove Emote Size Limit

README.md
The link to the releases in the firefox section of the readme didn't work
=> Updated Firefox releases link

src/Sites/youtube.com/Util/YouTube.ts, src/Sites/youtube.com/youtube.tsx
This fixes youtube's chat input box not updating after adding an emote.
Users no longer have to add a space after adding an emote for the chat input box to update.
=> Fix youtube input box not updating after adding emote from menu

changelog.md, src/Sites/youtube.com/youtube.tsx
Fixed an issue where the current users channel id was used for channel emotes instead of the channel's.
=> Fix youtube popout wrong channel id

src/Global/Util.ts, src/Sites/app/Settings/SettingsForm.tsx, src/Sites/twitch.tv/Components/BanSlider.tsx
Fixing bad imports of `material-ui`, which were importing the entire package in several instances, causing the output bundle size to swell into ridiculous sizes.
@Excellify 🤨
=> Fix Bad Imports

changelog.md, src/Sites/youtube.com/Runtime/Tokenizer.ts, src/Sites/youtube.com/Util/YouTube.ts
Fixed an issue with longer urls that were converted into https://example.com/something/asd... redirecting to the ... insead of the underlying full url.
Also removed the check for mod as the messages dont go through in the first place if the user isnt of the correct userlevel.
=> Fixed handling of long urls in YouTube chat

changelog.md, src/Sites/app/SiteApp.tsx
Fixes paints on firefox. 
Firefox dosnt allow you to access stylesheets that come from a different source than the origin. This includes all extensions as well as our own stylesheet for some reason.
Creates and returns a new stylesheet if the user is using firefox.
=> Fix paints on firefox

changelog.md, src/Sites/twitch.tv/Components/MessageTree.tsx, src/Sites/twitch.tv/Util/Twitch.ts, src/Style/Style.scss
Reinstates the ability to open the emote card by clicking twitch emotes. 
Closes: #18 
Closes: #184
=> Open emote card on click

changelog.md, src/Sites/app/SiteApp.tsx
Fixes a missing semicolon in the paints style builder that caused the color and drop shadow to not work when a color was included in the paint.
=> Fix paints style builder

changelog.md, src/Sites/twitch.tv/Util/Twitch.ts, src/Sites/twitch.tv/twitch.tsx
This adds all emotes to twitch's : auto-complete menu. Should be compatible with ffz, but haven't been able to test extensively.
=> Added support for auto completing emotes with :

changelog.md, src/Sites/twitch.tv/twitch.tsx
Fixes 2 issues with the colon-complete: 
1. Will no longer throw an error when recieving "cease" from ffz if the TwitchPageScript hasn't been initialized yet.
2. Colon-complete will now wait if twitch has not finished inserting its own emotes.
=> Colon-complete fixes

changelog.md, src/Sites/twitch.tv/twitch.tsx
Removing a change that was introduced by #193, which currently breaks the extension when the user starts with a twitch page other than a channel page
=> Remove breaking change introduced by #193

src/Style/Style.scss
yt adds a hidden countdown svg to the message-buttons elements and lazily sets a left value to align it with the send button. this fix adjusts that value to be in line with it once again after the 7tv emote button is rendered.
closes
#153 
#188
=> fixed position of youtube cooldown timer

src/Style/Style.scss
Fix for #147 
The parent element of the overlay element differ between https://dashboard.twitch.tv/ and https://www.twitch.tv/. This resulted in the positioning behaviour of the overlay differing on the 2 sites. This change should make sure the position of the overlay is consistent on the 2 sites.
=> Updated position CSS of the overlay class.

.github/workflows/build-pr.yaml, changelog.md, package.json, src/Sites/twitch.tv/Components/MessageRenderer.tsx, src/Sites/twitch.tv/Components/MessageTree.tsx, src/Sites/twitch.tv/Runtime/BaseChatListener.ts, src/Sites/twitch.tv/Runtime/ChatListener.ts, src/Sites/twitch.tv/Runtime/InputManager.tsx, src/Sites/twitch.tv/Runtime/VideoChatListener.ts, src/Sites/twitch.tv/Util/MessagePatcher.tsx, src/Sites/twitch.tv/Util/Twitch.ts, src/Sites/twitch.tv/twitch.tsx, yarn.lock
This pull request is for #23.
It adds 7TV support (emotes, painted names, etc.) for video chats (VODs, clips). Here's a summary of the changes:
Twitch videos, for whatever reason, use very different components, models, and layouts compared to live chats. In addition, the chat controller, which has references to chat and message APIs, is not available for video chats. A separate listener and additional types were introduced to address these differences.
I also had to change the Twitch script handle process to use the available React history object for detecting route/url changes. While setInterval() works fine-ish when there's only one listener being loaded, it causes a race condition (at least for me) where 7TV embeds and handlers are being unintentionally unloaded or overwritten when …
=> Added support for VOD and Clips on Twitch.

changelog.md, src/Sites/twitch.tv/Runtime/InputManager.tsx
This feature appears to now be broken for most users following Twitch's near-complete rollout of the Slate-based chat input. This is a simple fix to hook with the new input.
=> Fix the "Send same message twice" option

changelog.md, src/Global/API.ts
Fixing the issue which sometimes causes FFZ emotes to be considered as Twitch emotes, which causes either broken images or completely random emotes (for example FFZ's OMEGALUL becomes a twitch emote which is a man puking, because the ffz ID match the twitch id in the cdn.)
=> Fix FFZ emotes randomly breaking

changelog.md, src/Sites/app/SiteApp.tsx, src/Sites/twitch.tv/Runtime/InputManager.tsx, src/Sites/twitch.tv/Util/Twitch.ts, src/Sites/twitch.tv/twitch.tsx
Code cleanup of the spamming features such as duplicate message bypass and ctrl+enter.
- Now inserts the invisible character when sending a `PRIVMSG` through IRC rather than modifying the input box. 
- Ctrl+Enter now hooks into the chat controller and overwrites the message send function to keep the message in the box. Also implements its own cooldown to avoid getting rejections as a pleb
=> Improve spamming functionality

changelog.md, src/Sites/twitch.tv/Runtime/InputManager.tsx, src/Sites/twitch.tv/Util/Twitch.ts
Fixing an issue which broke the reply feature on twitch. This was caused by a secondary parameter in the input controller's `onSendMessage` function being discarded by 7TV's IRC handler.
Fixes #243
=> Fix for replying on twitch

src/Style/Style.scss
Before:
After:
I don't know about you, but it has been infuriating me since the first moments 7TV started to work on YouTube.
=> Changes so your cursor turns into a pointer for the YouTube 7TV emote button

changelog.md, src/Global/API.ts, src/Global/EmoteStore.tsx
Some FFZ emotes only provide a 1x resolution. This filters both the Emote object and patches the rendering.
Fixes #252
=> Filter out missing urls

src/Sites/twitch.tv/Util/MessagePatcher.tsx
This fixes the rerendering of messages send by the user. Not sure of the implications of not clearing the patcher, but dosn't seem to break anything immediately. Not including changelog in case you want to improve upon this. Ill be gone for most of the rest of the day.
=> Temporary workaround to messages sendt by the user being rerendered.

CHANGELOG-nightly.md, locale/en_US.yaml, src/site/site.ts, src/site/twitch.tv/modules/emote-menu/EmoteMenu.vue, src/site/twitch.tv/modules/emote-menu/EmoteMenuTab.vue
Adding a button under the Twitch tab of the emote menu, to toggle the native twitch menu. (as a workaround for seeing locked emotes)
=> EmoteMenu: native toggle button

src/assets/style/global.scss, src/site/global/settings/CategoryDropdown.vue, src/site/global/settings/Settings.ts, src/site/global/settings/SettingsMenu.vue, src/site/global/settings/SettingsNode.vue, src/site/global/settings/SettingsViewConfig.vue, src/site/global/settings/SettingsViewConfigCat.vue, src/site/twitch.tv/modules/settings/SettingsModule.vue
Making the settings menu feel more responsive by highlighting the current sub-category in view on the sidebar
=> settings menu: subcategory highlight

src/background/background.ts
Making the upgrade-driven onboarding popup only appear when the user is interacting with twitch.tv (ie opening a new twitch tab, or navigating twitch in any way)
=> Contextual Onboarding Upgrade Popup

src/composable/chat/useChatMessages.ts, src/site/global/settings/control/FormSlider.vue
This improves the visual feedback when chat unbuffers after previously being paused, so that it looks like the chat instantly unbuffered while avoiding a page stall.
This also fixes an issue with the Slider settings control, which caused it to store values as strings rather integers. This led to smooth scrolling logic being used unnecessarily.
=> Improve Chat Unbuffering

CHANGELOG-nightly.md, src/composable/useFrankerFaceZ.ts
This is wrong behavior, as this actually just stops FFZ from allowing Twitch sub emotes to be used in colon complete and other areas, and does not cause any known clashing.
=> Don't disable emotes in FFZ

CHANGELOG-nightly.md, src/site/twitch.tv/modules/chat-vod/ChatVod.vue
Also properly handle when messageRef's are undefined as this will cause an immediate crash due to the destructuring operator {}, which can happen when a condition is not met for a message to be considered valid, or when the array is oversized.
=> Fix VOD chat crashing while the user is logged out

.github/workflows/ci.yaml, src/site/twitch.tv/modules/chat/ChatController.vue, src/site/twitch.tv/modules/chat/components/message/EmoteTooltip.vue, src/site/twitch.tv/modules/mod-logs/ModLogs.vue
1. Makes the "Mod Logs" use the same amount of blur as the emote menu. (was very annoying)
2. Smaller "Mod Logs" text, so it looks better.
3. Gives some padding to the big emote image so it looks better
4. Adjusts the "Chat paused" popup thing to look better in light mode.
5. Gets rid of the pointless ugly line below the emote name
=> Improve some styling

CHANGELOG-nightly.md, src/site/twitch.tv/modules/chat/components/message/UserMessage.vue
Fixes the ungodly flickering when hovering over a message ban state message sometimes.
Changed "display: none;" to "visibility: hidden"
Bug Issue:
Bug Video:
https://user-images.githubusercontent.com/76515905/230157080-ed58cdfd-dc35-46f9-a46c-729319c9449a.mp4
=> Fixed message ban state message from flickering

CHANGELOG-nightly.md, CHANGELOG.md, package.json, src/assets/svg/icons/CopyIcon.vue, src/site/twitch.tv/modules/chat/ChatModule.vue, src/site/twitch.tv/modules/chat/components/message/UserMessageButtons.vue, src/ui/UiCopiedMessageToast.vue
Toggleable 'Copy' icon to copy a chat message. Icon appears next to reply/pin icons:
Clicking the icon copies the chat message and shows a toast for 1 second confirming the message was copied:
**This copies purely the chat message, so the clipboard in the above example results in: "Hello"**
This feature is toggleable and true by default, a new subcategory named "Message tools" in "Chat" settings is added as I was unsure which subcategory this would fit in:
It is understandable if this feature is not approved as some chats may not appreciate easier copy pastas... but there are some chats who would be a fan of it. Let me know if I should remove feature 1 and just keep feature 2 as I believe feature 2 is useful.
Tooltips for the reply/pin/copy icons on mouse hover:
This feature utilizes the …
=> Add 'Copy' Icon to chat messages, Add tooltip to message icons

package.json, src/site/twitch.tv/modules/chat-input/ChatInput.vue, src/site/twitch.tv/modules/chat/ChatList.vue, src/site/twitch.tv/modules/chat/components/message/Emote.vue, src/site/twitch.tv/modules/emote-menu/EmoteMenu.vue, src/site/twitch.tv/modules/emote-menu/EmoteMenuModule.vue, src/site/twitch.tv/modules/emote-menu/EmoteMenuTab.vue
Making some changes and fixes on performance issues
---
=> Performance Tweaks

CHANGELOG-nightly.md, src/site/global/settings/SettingsNode.vue
My twitch has an inline style tag that sets `.control { position: absolute; } `, which results in the settings menu being unusuable.
I thought it was a compatibility issue as there's no open Issue about that, so I disabled all other twitch extensions and that didn't fix the issue. This is quite a serious issue and since nobody else reported it I guess it's an edge case with my system.
Anyway, this fix is just a single line of css that shouldn't conflict with anything else. I didn't bother to create an open issue for it, I hope that's not a problem.
For reference, this is what it looks like when I scroll down in the settings:
=> Fix setting controls not scrolling with the rest of the settings menu

CHANGELOG-nightly.md, CHANGELOG.md, package.json, src/site/twitch.tv/modules/chat-input/ChatInput.vue
Fixing an issue which causes tab-completion to break after a chater's name becomes the current token
=> fix: tab-complete chatters

CHANGELOG-nightly.md, package.json, src/common/chat/Tokenizer.ts, src/site/twitch.tv/index.ts, yarn.lock
Closes #488
Changed the link regex to only match messages which starts with http, https or www. 
It won't be possible to write google.com in chat which was previously rendered as https://google.com
=> fix: decimal no longer rendered as link

CHANGELOG-nightly.md, src/site/twitch.tv/modules/chat/ChatList.vue, src/site/twitch.tv/modules/chat/ChatModule.vue
Adds an opt-in option to see basic timeout and ban messages directly in the chat without the need of mod logs
=> Add option to show timeouts and bans directly in the chat

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Adds GitHub issue forms to the repository, reading issues currently is a mess.
[GitHub issue forms docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)
=> Added issue forms

CHANGELOG-nightly.md, src/site/global/components/EmoteCard.vue
It seems that `onResult` is not called or is called too early when the actor is already cached, so let's use watch instead
=> fix: emote card actor

CHANGELOG-nightly.md, src/site/twitch.tv/modules/chat-input/ChatInput.vue, src/site/twitch.tv/modules/chat-input/ChatInputModule.vue
Allow the user to select if they want to filter emotes by `starstWith` or `includes` in colon-completion list and tab-completion carousel for each independently, defaults stay the same
=> colon-completion list and tab-completion carousel mode options

CHANGELOG-nightly.md, src/common/chat/Tokenizer.ts, src/site/twitch.tv/modules/chat/ChatModule.vue, src/site/twitch.tv/modules/chat/components/message/UserMessage.vue
Adds a toggle option to show/hide BTTV and FFZ emote modifiers, implements #482
=> feat: add option to toggle hiding emote modifiers

CHANGELOG-nightly.md, src/site/twitch.tv/modules/chat/ChatList.vue, src/site/twitch.tv/modules/chat/ChatModule.vue
Adds a option in highlights/built-in to highlight your own chat messages.
Setting option:
Highlight image:
Closes #470
=> Add option to highlight your own messages

CHANGELOG-nightly.md, src/common/Constant.ts, src/site/App.vue, src/site/youtube.com/YouTubeSite.vue, src/site/youtube.com/modules/chat/ChatAutocomplete.vue, src/site/youtube.com/modules/chat/ChatController.vue, src/site/youtube.com/modules/chat/ChatModule.vue
This changes how youtube is hooked to query `chatframe` from `window.frames` and scoping to the inner window's frame content. 
This reinstates youtube functionality which was previously disabled in v3.0.3.
=> Handle YouTube Chat Iframe without `all_frames`

CHANGELOG-nightly.md, package.json, src/composable/useUserAgent.ts, src/store/main.ts
Firefox [has supported AVIF images for a while](https://www.mozilla.org/en-US/firefox/93.0/releasenotes/), but it didn't support animated sequences. As of Firefox 113, [animated sequences are enabled by default](https://www.mozilla.org/en-US/firefox/113.0/releasenotes/).
=> feat: Enable AVIFs on Firefox >= v113 by default

manifest.config.ts
Removing `cookies` from permissions list as this method of authentication isn't yet implemented, prompting a rejection in the Chrome Web Store.
=> manifest: remove cookies permission

.github/dependabot.yml
Ignoring patch versions for dependabot notices to avoid flooding pull requests.
=> dependabot: ignore patch versions

CHANGELOG-nightly.md, package.json, src/assets/svg/icons/OpenLinkIcon.vue, src/site/global/components/EmoteCard.vue
Add an icon with a link to open the emote in a new tab directly from the emote card.
=> Add link to emote in emote card

CHANGELOG-nightly.md, src/site/twitch.tv/modules/chat/components/user/UserCard.vue
When there is long text with no spaces, the UserCard box overflows. 
The problem was fixed with a minor CSS modification.
=> fix: UserCard content box overflow issue

CHANGELOG-nightly.md, src/site/twitch.tv/modules/chat/ChatController.vue
Adding `z-index: 1;` to the chat scroller so that it can't spread into the layout change into Twitch UI
Closes #554
=> fix: chat scroller visible viewer list

src/site/twitch.tv/modules/sidebar-previews/SidebarPreviewsModule.vue
Unmounting the sidebar previews code if the option is disabled. This is to investigate if hooks used by this feature are causing a Twitch crash
=> sidebar previews: unmount if disabled

CHANGELOG-nightly.md, src/site/twitch.tv/modules/chat/ChatData.vue, src/worker/worker.events.ts
This fixes an occasional issue when an IDB push occurs which led to the channel sets live query triggering, resetting data of emote providers and causing the channel sets on other tabs to be disabled.
=> fix: channel sets resetting when a new tab joins

CHANGELOG-nightly.md, src/site/site.app.ts
This fixes an issue where the extension's local stylesheet remained in place after the site script starts in hosted mode. This occasionally leads to style clashes where outdated local styles interfere with those in more recent hosted builds.
=> hosted-deploy(fix): remove built-in stylesheet

CHANGELOG-nightly.md, src/app/chat/UserMessage.vue
This fixes mod icons not appearing, a bug introduced in #622
=> fix: missing mod icons

CHANGELOG-nightly.md, src/app/emote-menu/EmoteMenu.vue
this fixes some styling issues that arose when the emote menu was split into its own generalized component in #646
=> tweak unified emote menu styling

CHANGELOG-nightly.md, src/site/kick.com/modules/chat/ChatMessage.vue, src/site/kick.com/modules/chat/ChatModule.vue
this adds a `watchEffect()` call on message to re-tokenize on prop changes, fixing inconsistent behavior when message history loads before emotes are available
=> site/kick(fix): historical messages

CHANGELOG-nightly.md, src/site/kick.com/modules/chat/ChatMessage.vue
Addressing an oversight in the token reconstruction which failed to handle scenarios where multiple text fragments exist where non-text tokens are skipped. This adds a `WeakMap` to store tokens linked to the relevant containing element. This fixes an issue where all text tokens would be replaced with the last seen text fragment when mixed with native emotes
=> site/kick(fix): message local tokens

CHANGELOG-nightly.md, src/site/kick.com/modules/chat/ChatAutocomplete.vue
Prevents the input on Kick from becoming non-contenteditable and refocusing after a message is sent
Closes #699
=> feat(kick): re-focus input in slow mode

CHANGELOG-nightly.md, src/site/twitch.tv/modules/hidden-elements/HiddenElementsModule.vue, src/site/twitch.tv/modules/hidden-elements/hiddenElements.ts
Twitch just introduced the new feature "hype chats" (see: https://help.twitch.tv/s/article/hype-chat-faq).
This feature can be really annoying for casual viewers considering the bright colors and constant pin above the chat.
Therefore this PR aims to introduce options to remove most of the hype chat features.
However, this change does not affect the solid boxes of "hype chat"-messages in the chat.
Both options disable the respective site elements via their unique class or attribute. 
For the "Hype Chat"-button, the attribute "aria-label" is used as unique identification.
For the "Pinned list of hype chats", the element's class name proves unique.
Both new options have been tested in various combinations with other existing options and work flawlessly.
The middle button (lightning icon) is …
=> Add options to hide pinned hype chat list and hype chat button

CHANGELOG-nightly.md, src/app/chat/UserCard.vue
this fixes a crash when fetching user card logs as a moderator and also adds contrast to the user paint label text
=> user-card(fix): crash on logs fetch

CHANGELOG-nightly.md, src/worker/index.ts, src/worker/worker.events.ts
This fixes a mistake causing the EventAPI connection to be closed with an `Already Subscribed` error due to the `syncSubscriptions()` method being called upon the initial connect.
=> worker(fix): eventapi initial connect failure

CHANGELOG-nightly.md, package.json, src/site/twitch.tv/modules/chat/ChatModule.vue
This increases the default value for message batching on Twitch to be more inline with native chat
=> twitch/chat(tweak): default msg batch 150->250

CHANGELOG-nightly.md, src/app/emote-menu/EmoteMenu.vue, src/app/emote-menu/EmoteMenuSet.vue, src/app/emote-menu/EmoteMenuTab.vue, src/site/twitch.tv/modules/emote-menu/EmoteMenu.vue
Adding some QoL to the emote menu
- Arrow Up/Down to switch between providers
- Automatically focus the input box upon opening
- Allow shifting tab focus forward, rather than only backward, during search
- Reinstate Ctrl+E as a shortcut to open the menu
-
=> emote-menu(tweak): qol & shortcuts

CHANGELOG-nightly.md, src/app/chat/EmoteTooltip.vue
This fixes emote tooltips being squished when hovering on the far right side
Closes #560 
Pull request originally by @saliven at #612
=> twitch/chat(fix): emote tooltip squish

CHANGELOG-nightly.md, src/app/emote-menu/EmoteMenu.vue, src/site/twitch.tv/modules/emote-menu/EmoteMenuModule.vue
Closes #670 
Added setting to choose the default emote menu tab on initial open.
Default value for setting is the same as the original hard-coded value.
=> Choose Default Emote Menu Tab

CHANGELOG-nightly.md, src/app/settings/SettingsNode.vue, vite.config.ts
adds #576 
taking suggestions on css formatting and handling custom components/ignores
=> settings(feat): reset to default value

CHANGELOG-nightly.md, src/app/emote-menu/EmoteMenuSet.vue
Adjusts the width of the emote tiles in the emote menu so they tile correctly.
=> Fix emote tile width

CHANGELOG-nightly.md, locale/en_US.yaml, src/app/chat/UserCard.vue
The issue occurs when the "Hide Subscription Status in Chat Viewer Card" option is enabled in Twitch settings.
It says "Tier 1 - Subscribed for 0 months" no matter how long or which tier you have subscribed.
Before: 
After: 
This gives more accurate information about the subscription status.
=> fix: UserCard "hidden subscription status" message

CHANGELOG-nightly.md, locale/en_US.yaml, src/app/emote-menu/EmoteMenuTab.vue
If user does not have any emotes favorited, there is no indication on how to favorite an emote.
This PR adds a small display on the favorites menu to suggest Alt-clicking an emote to favorite one.
I honestly have no idea what I am doing and have never used vue before so I'm sure there's some terrible bug
I'm noticing provider issues and can't tell if it's my own code. Certain emotes won't show up when changing between streams/refreshing but the same behavior occurs when running main locally, I think it's just being blocked by CORS. If this is just a localhost issue then hopefully everything is fine...?
=> feat: Add check for favorite emotes and display helpful message

CHANGELOG-nightly.md, src/assets/gql/tw.chat-delete.gql.ts, src/composable/chat/useChatModeration.ts
Fixed the functionality of the delete message function to use Apollo instead of IRC, this conforms with how Twitch natively handles deleting messages. This will also fix issues where users are failing to delete messages seen in the image below.
Issue:
=> Fix delete message functionality

.stylelintrc, CHANGELOG-nightly.md, package.json, src/composable/useCosmetics.ts, src/composable/useWorker.ts, src/db/idb.ts
Fixing a few issues involving personal emote sets, where a lack of expiration leads to eventual clogging of IndexedDB and reduced performance, as well as that users with multiple personal emote sets couldn't actually use them both at once.
=> fix: personal emote sets expire & concurrent use

CHANGELOG-nightly.md, src/app/options/Options.vue
I have fixed the problem that made the extension menu look like a line. Removing a display that caused the issue.
=> fix: Extension menu don't show in chrome

CHANGELOG-nightly.md, src/site/twitch.tv/modules/avatars/AvatarsModule.vue
This reinstates animated avatars which were broken due to a change in Twitch's website
=> fix: animated avatars

.github/workflows/ci.md, CHANGELOG-nightly.md, src/common/ReactHooks.ts, src/site/twitch.tv/modules/chat-input/ChatInputModule.vue
Adds support for react 18 and adds a completely unrelated ci doc I wrote.
=> fix(twitch): react 18 support

CHANGELOG-nightly.md, src/app/chat/msg/14.SubscriptionMessage.vue, src/app/chat/msg/15.Resubscription.vue, src/app/chat/msg/21.SubGift.vue, src/app/chat/msg/35.SubMysteryGift.vue, src/app/chat/msg/49.AnnouncementMessage.vue
Fixed an issue where a channel's accent colors were not used in chat. It caused messages like announcements, (re)subscriptions and gifted subscriptions to fall back onto a white accent color or none. See a few snippets below:
which should now look like:
and
should now look like this:
=> fix(twitch): chat accent color

CHANGELOG-nightly.md, src/app/chat/EmoteTooltip.vue
If an emote had a long alias and was hovered over, the alias would overflow outside of the tooltip. See the following example:
which should now look like the following:
=> fix: wrap emote alias

CHANGELOG-nightly.md, src/site/twitch.tv/modules/chat-vod/ChatVod.vue, src/site/twitch.tv/modules/chat/ChatList.vue
If a user sends a cheer in chat it is meant to be turned into an emote with it's text colored differently. It can be sent as it's lowercase and uppercase variant (e.g. "cheer1" & "Cheer1"). 7TV currently seems to only support the uppercase variant.
See the following example (msg lit. "cheer123456 Cheer123456"):
which should now look like this:
Should fix: #453
=> fix(twitch): support lowercase cheers

CHANGELOG-nightly.md, src/site/twitch.tv/modules/avatars/AvatarsModule.vue
Scrolling through the streams inside of a specific category can lock up after initial page load / while scrolling down. 
This issue seems to happen because the `AvatarsModule` patches and re-renders the avatars after updating their properties. However, it seems like during re-rendering it grabs a virtual node holding the cards where you actually scroll through. Updating that container (instead of it's parent holding it's ref) will cause [simplebar](https://github.com/Grsmto/simplebar) to break and delete containers.
https://github.com/SevenTV/Extension/assets/29018740/98dfe5f6-176d-498a-88d6-af05ab7f1590
which should now work like this:
https://github.com/SevenTV/Extension/assets/29018740/09d9cc74-69b4-4185-9b28-2701547ede6f
Should fix: #635
=> fix(twitch): experiment category scroll

CHANGELOG-nightly.md, src/app/chat/UserMessage.vue
Using the 24-hour timestamp format would cause the time to start counting beyond the 24 hour mark. It would result in the time to display "24:01:59" as opposed to "00:01:59". See the following example:
which should now display instead:
Should fix #929
=> fix(chat): broken 24h timestamp

CHANGELOG-nightly.md, src/app/chat/UserMessageButtons.vue, src/common/Transform.ts, src/common/chat/ChatMessage.ts, src/site/twitch.tv/modules/chat/ChatList.vue, src/site/twitch.tv/modules/chat/components/tray/ChatTray.ts, src/site/twitch.tv/modules/chat/components/tray/ReplyTray.vue, src/site/twitch.tv/modules/chat/components/tray/tray.d.ts, src/types/twitch.messages.d.ts
Opening / replying to threads would only allow you to view up to a maximum of 2 messages (the main message and one reply). 
This is fixed by using the tray's thread props instead of just it's parent props. This PR also fixes the issue where message buttons  (copy & reply) were not being displayed when hovered over inside of a thread tray.
See the following example of this implementation:
https://github.com/SevenTV/Extension/assets/29018740/4d6312c7-b0 …
=> fix(twitch): replies in thread

CHANGELOG-nightly.md, src/site/kick.com/composable/useRouter.ts, src/site/kick.com/modules/chat/ChatEmoteMenu.vue, src/site/kick.com/modules/chat/ChatModule.vue
A simple UI update by Kick changed the chat input container where the emote picker icon was being placed. This PR simply updates it to the new one. 
Additionally, the previous implementation never reset the channel state after leaving a channel. So re-entering the same channel (e.g. by going to the homepage and back) would cause the emote picker to also not rerender. Along with that change, if no message was dispatched by the room it would also cause the channel to never be assigned. These are both fixed by this PR.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a …
=> fix(kick): emote menu button

CHANGELOG-nightly.md, src/worker/worker.http.ts
Currently, when subscribing to the user events (AFAIK only used to listen for changes to which emote-set is selected) the user-id of the respective platform is passed as the `object_id` instead of the 7tv user-id.
https://github.com/SevenTV/Extension/blob/a98e3653a0d0714f945e57d20daf53f2cf5834f0/src/worker/worker.http.ts#L156-L159
This PR just uses the 7tv user-id as the `object_id` instead.
Example …
=> fix: wrong id used when subscribing to user events

CHANGELOG-nightly.md, src/app/chat/UserTag.vue, src/site/twitch.tv/modules/chat/ChatController.vue, src/types/twitch.d.ts
Entering a chat sometimes caused badges to not show up (generally with historic messages). This was caused because the badge sets weren't exposed yet with the way they were extracted from it's component. The old implementation relies on a message to already be displayed, thus having no messages would cause the badge sets to not be assigned until a message is to be displayed.
This is however fixed by using the chat room component instead. It exposes the badge sets through it's props instead of it's children.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder …
=> fix(twitch): badges not displayed

CHANGELOG-nightly.md, src/site/twitch.tv/modules/chat/ChatController.vue
When opening up a stream, historic messages would not always display whenever the chat was loaded in. If the chat module was loaded before the historic messages were loaded in, it would not have access to them and thus end up not rendering any. This is however fixed by simply rendering after they have been loaded in.
--
=> fix(twitch): load chat history

CHANGELOG-nightly.md, src/site/twitch.tv/modules/hidden-elements/HiddenElementsModule.vue, src/site/twitch.tv/modules/hidden-elements/hiddenElements.ts
Twitch seems to have remove the "React" feature which caused some metadata buttons to break. This PR simply removes the option to hide the button.
--
=> refactor(twitch): remove hide React button option

CHANGELOG-nightly.md, src/common/chat/ChatMessage.ts, src/composable/chat/useChatMessages.ts, src/composable/usePubSub.ts, src/site/twitch.tv/modules/chat/ChatList.vue, src/site/twitch.tv/modules/chat/ChatModule.vue, src/site/twitch.tv/modules/chat/ChatPubSub.vue, src/site/twitch.tv/modules/chat/components/tray/ChatTray.ts
When a suspicious user sent a message after being marked as suspicious, the extension would not persist in marking that user as suspicious after new messages were sent. Along with that, returning users were not being highlighted anymore. 
This is caused by Twitch moving chat highlights to pubsub (instead of tmi) which allowed me to add support for raider highlights as well. Another issue caused the pubsub to not re-add listeners after reconnect. See the images below for examples.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look …
=> fix(twitch/chat): low trust / returning user highlight

CHANGELOG-nightly.md, src/app/chat/UserCard.vue, src/site/twitch.tv/modules/chat-vod/ChatVod.vue, src/site/twitch.tv/modules/chat/ChatList.vue
Fixed an issue causing messages to not immediately display logins if the user has an international display name. Along with that, the user cards now also display their logins.
Before:
https://github.com/SevenTV/Extension/assets/29018740/9ae68eda-ac37-4038-a517-149c538bce4f
After:
https://github.com/SevenTV/Extension/assets/29018740/68177380-77c8-4e67-a005-4bcec037ed62
Before:
After:
=> fix(twitch): display logins with international display names

src/site/site.app.ts, src/types/app.d.ts
A minor change made in https://github.com/SevenTV/Extension/commit/4c0f3b97d89f0f1166af50710f3a50ba4075309f caused the builds deployed after `3.0.15` to use the `hosted` property as opposed to `remote` exposed on the `seventv` global. Since the older build (3.0.9) still exposes `remote` it causes `hosted` to never be defined. Nightly builds are not affect because their latest store build was version `3.0.15.1000`.
--
=> fix: hosted mode fallback

CHANGELOG-nightly.md, src/common/Tokenize.ts, src/common/chat/Tokenizer.ts
Using an emote name that contains property keys of an object prototype causes the Tokenizer to resolve to that property instead of an actual emote. E.g. using the text `constructor` or `__proto__` will result in an empty "emote". The same applies to mentions. See the images below for examples.
Before:
After:
=> fix(tokenizer): empty emote

CHANGELOG-nightly.md, package.json, src/common/Image.ts, src/common/Transform.ts
After hovering over a twitch emote (global or sub) at 1x scaling this emote was displayed larger than normal in chat afterwards (37x37 instead of the usual 28x28). This happened until the page was refreshed.
Reason for bug was using 1x, 2x and 3x for twitch srcset. 3x and 4x for twitch are both 112x112 though.
Changing to 1x, 2x and 4x and adjusting the twitch emote converter fixed this problem.
old behaviour: …
=> fix: Fixed an issue where twitch emotes were larger after hover

CHANGELOG-nightly.md, src/site/twitch.tv/modules/chat-vod/ChatVod.vue
Navigating to a VOD will cause the extension to render message timestamps twice. This does not occur when going to a VOD directly by URL. See the images below
Before:
After:
=> fix(twitch/vod-chat): vod chat double timestamp

CHANGELOG-nightly.md, src/app/chat/UserTag.vue, src/site/twitch.tv/modules/chat/ChatModule.vue
Added option to hide 7TV badges in chat.
A slider option to show or hide 7TV badges was added in the settings under Appearance -> Vanity. Default setting is show.
Settings:
activated:
disbaled:
=> feat: Added option to hide 7TV badges in chat

CHANGELOG-nightly.md, package.json, src/common/Transform.ts, src/types/app.d.ts
Only static FFZ emotes are currently supported by 7TV. For animated emotes only the static version is used, probably because FFZ itself only added support for them rather recently. Because of that 7TV should add support for animated FFZ emotes as well.
The FFZ API has a field "animated" which returns a map of DPI scales to animated emote URLs and is null if the emote is not animated. This field was added to our interface and the transformer adjusted …
=> Feat: Animated FFZ emote support

src/site/kick.com/KickSite.vue, src/site/kick.com/composable/useUserdata.ts, src/site/kick.com/modules/auth/AuthButton.vue, src/site/kick.com/modules/auth/AuthModule.vue
=> Feature/kick - Auth + Linking

CHANGELOG-nightly.md, src/app/emote-menu/EmoteMenu.vue, src/site/kick.com/modules/chat/ChatAutocomplete.vue, src/site/twitch.tv/modules/chat-input/ChatInput.vue, src/site/twitch.tv/modules/chat-input/ChatInputCarousel.vue
This change fixes an issue where history navigation (up/down arrow key on chat box) was accidentally triggered during IME composition.
IME is a tool for writing Japanese (and other languages I'm not aware of) where users can select the word they want to enter from the list of words that match the pronounciation given by the user's keystrokes--this process is called composition.
It's pretty common to press arrow key during composition, and that has …
=> fix: ignore composing key events to prevent unintended behavior

src/common/Image.ts
Removed https because it is not needed and may cause problems in the future
-
=> Removed scheme

CHANGELOG-nightly.md, locale/en_US.yaml, package.json, src/site/global/components/EmoteCard.vue
To make emote artists more visible I added a link to the emote creator of 7TV emotes to the emote card.
=> Adding link to emote creator's 7TV profile to emote cards

CHANGELOG-nightly.md, src/app/chat/MessageTokenMention.vue, src/app/chat/UserTag.vue
When colored mentions are turned off (new default value) mentions are not clickable anymore to open the usercard, because they were rendered as just normal text. This was fixed in this PR
=> Fix: fixed mentions not being clickable when colored mentions are turned off

CHANGELOG-nightly.md, CHANGELOG.md, package.json, src/app/chat/UserCard.vue, src/site/twitch.tv/modules/avatars/AvatarsModule.vue, src/types/app.d.ts
Implements/fixes animated avatars for the 7TV usercard
=> Animated avatar in user card

CHANGELOG-nightly.md, src/common/Constant.ts
The unicode tag that was appended to messages to prevent the duplicate message check was getting dropped by Twitch after an update. By changing the tag from `\u{e0000}` to `\u{34f} ` the check should work again (and also in the future since emojis rely on the tag)
=> FIX - replaced Unicode tag for duplicate message check
